server:
  port: 8081
spring:
  application:
    name: platform-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://10.99.1.106:3306/platform?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
      hibernate:
        ddl-auto: none
        show-sql: true
        open-in-view: true
  dubbo:
      application:
        name: platform_provider
      registry:
        address: zookeeper://10.99.1.106:2181
      protocol:
        port: 20880
      scan: com.css.platform
swagger:
  title:  platform组api文档
  version: 1.0
  basePackage: com.css.platform.web

